services:
  - type: web
    name: spam-classifier-streamlit
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    plan: free
    autoDeploy: true
